### ISSUE TITLE
unauthorized response header setting

### ISSUE THREAD

**Issue by txgo** [StephanDollberg/go-json-rest-middleware-jwt#1]
A http auth basic login dialog show up as the settting in unauthorized response header, may be just a json error response is better.

```
func (mw *JWTMiddleware) unauthorized(writer rest.ResponseWriter) {
  writer.Header().Set("WWW-Authenticate", "Basic realm="+mw.Realm)
  rest.Error(writer, "Not Authorized", http.StatusUnauthorized)
}
```

For example:

```
func (mw *JWTMiddleware) unauthorized(writer rest.ResponseWriter) {
  writer.Header().Set("X-Authenticate", "Basic realm="+mw.Realm)
  rest.Error(writer, "Not Authorized", http.StatusUnauthorized)
}
```

**Comment by StephanDollberg** [comment]
Thanks for the hint. You are very right.

However, I think changing `Basic realm` to `JWT realm` makes more sense. This also mirrors what the [django-rest-framework](https://github.com/GetBlimp/django-rest-framework-jwt/blob/master/rest_framework_jwt/authentication.py#L86) does.

Will fix this later today. Thanks again.
