### ISSUE TITLE
How to post more data?

### ISSUE THREAD

**Issue by nwaycn** [StephanDollberg/go-json-rest-middleware-jwt#15]
Hi 
     I use go-json-rest for me apis,  bug I don't know how to post more than one field data ,so this:

 curl -d {"a":"1","b":"2"} -H "Authorization:Breare eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NjUyMDcyODUsImlkIjoiYWRtaW4iLCJvcmlnX2lhdCI6MTQ2NTIwMzY4NX0.DQygZY8z2zXVccHqfb76jLZLMBqtnpQ4JLwJHS-BW0" http://192.168.1.115:8082/api/mytest/1002

**Comment by StephanDollberg** [comment]
Hi @nwaycn,

do you want the data to be part of the jwt token or do you just want to post it?

**Comment by nwaycn** [comment]
@StephanDollberg ，
I want to post data to my api ,but it tip me :  Bad Content-Type or charset, expected 'application/json'  ,if I modified it so:  
 curl -d {"A_var":"1002","B_var":"1003"} -H "Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NjUyNTc5NDAsImlkIjoiYWRtaW4iLCJvcmlnX2lhdCI6MTQ2NTI1NDM0MH0.ZUatYbG8pwJqUoONZGh_LJHjZlNbyAiv5WwNMZ4-VCk" http://192.168.1.115:8082/api/mytest
curl: (6) Could not resolve host: B_var
{
  "Error": "Bad Content-Type or charset, expected 'application/json'"
}

other:
 curl -d {"A_var":"1002","B_var":"1003"} -H "Content-Type: application/json" -H "Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NjUyNTc5NDAsImlkIjoiYWRtaW4iLCJvcmlnX2lhdCI6MTQ2NTI1NDM0MH0.ZUatYbG8pwJqUoONZGh_LJHjZlNbyAiv5WwNMZ4-VCk" http://192.168.1.115:8082/api/mytest
curl: (6) Could not resolve host: B_var
{
  "Error": "invalid character 'A' looking for beginning of value"
}
