### ISSUE TITLE
jwt.Claims  does not support indexing

### ISSUE THREAD

**Issue by kejordan** [StephanDollberg/go-json-rest-middleware-jwt#17]
Jwt released an update that makes lines like "idInterface := token.Claims["id"]" invalid.  It looks like the workaround is: 

claims := token.Claims.(jwt.MapClaims) 
idInterface := claims["id"]

But doing this breaks my authorization (the authorization my boss wrote months ago).  I'm brand new to go, so I'm wondering if my workaround is flawed.  If not, the authorization is just broken and I can go down that troubleshooting path.  Thanks for your help!

**Comment by StephanDollberg** [comment]
Hi @kjordan88 ,

Yes, I am aware of the update. Now that the update is out I will start porting to v3 and at the same time make some breaking changes.

You currently shouldn't be affected by simply using Go vendoring. If you are on an older version, you can manually vendor by checking out the version that I have vendored.

**Comment by kejordan** [comment]
Perfect - thanks so much!
