### ISSUE TITLE
is it possible to add user role in the token?

### ISSUE THREAD

**Issue by john-qin** [StephanDollberg/go-json-rest-middleware-jwt#2]
I need to check if user is admin or user.  is it possible to include user role in the token and request header, so we can easily get it like what we did for username r.Env["REMOTE_USER"].(string)

UPDATE:

here's my solution. may not be a good one, but it works for me. I modified the Authenticator function to support role.

https://gist.github.com/6384ae30aecdd0974c2b.git

following lines are changed.
42,  115, 116, 123, 180

in your authenticator function, you need to return another value for role

```
jwt_middleware := jwt.JWTMiddleware{
    Key:        []byte("DGFER#$4543_d"),
    Realm:      "jwt auth",
    Timeout:    time.Hour,
    MaxRefresh: time.Hour * 24,
    Authenticator: func(username string, password string) (bool, string) {
        if username == "webadmin126" && password == "admin" {
            return true, "admin"
        }

        return false, ""
    },
}
```

now,you should see user role

```
func handle_auth(w rest.ResponseWriter, r *rest.Request) {
w.WriteJson(map[string]string{"authed": r.Env["REMOTE_USER"].(string), "role": r.Env["USER_ROLE"].(string)})
}
```

**Comment by john-qin** [comment]
here's my solution. may not be a good one, but it works for me.  I modified the Authenticator function to support role.


package jwt

import (
	"github.com/ant0ine/go-json-rest/rest"
	"github.com/dgrijalva/jwt-go"

	"errors"
	"log"
	"net/http"
	"strings"
	"time"
)

// JWTMiddleware provides a Json-Web-Token authentication implementation. On failure, a 401 HTTP response
// is returned. On success, the wrapped middleware is called, and the userId is made available as
// request.Env["REMOTE_USER"].(string).
// Users can get a token by posting a json request to LoginHandler. The token then needs to be passed in
// the Authentication header. Example: Authorization:Bearer XXX_TOKEN_XXX
type JWTMiddleware struct {
	// Realm name to display to the user. Required.
	Realm string

	// signing algorithm - possible values are HS256, HS384, HS512
	// Optional, default is HS256.
	SigningAlgorithm string

	// Secret key used for signing. Required.
	Key []byte

	// Duration that a jwt token is valid. Optional, defaults to one hour.
	Timeout time.Duration

	// This field allows clients to refresh their token until MaxRefresh has passed.
	// Note that clients can refresh their token in the last moment of MaxRefresh.
	// This means that the maximum validity timespan for a token is MaxRefresh + Timeout.
	// Optional, defaults to 0 meaning not refreshable.
	MaxRefresh time.Duration

	// Callback function that should perform the authentication of the user based on userId and
	// password. Must return true on success, false on failure. Required.
	Authenticator func(userId string, password string) (bool, string)

	// Callback function that should perform the authorization of the authenticated user. Called
	// only after an authentication success. Must return true on success, false on failure.
	// Optional, default to success.
	Authorizator func(userId string, request *rest.Request) bool
}

// MiddlewareFunc makes JWTMiddleware implement the Middleware interface.
func (mw *JWTMiddleware) MiddlewareFunc(handler rest.HandlerFunc) rest.HandlerFunc {

	if mw.Realm == "" {
		log.Fatal("Realm is required")
	}
	if mw.SigningAlgorithm == "" {
		mw.SigningAlgorithm = "HS256"
	}
	if mw.Key == nil {
		log.Fatal("Key required")
	}
	if mw.Timeout == 0 {
		mw.Timeout = time.Hour
	}
	if mw.Authenticator == nil {
		log.Fatal("Authenticator is required")
	}
	if mw.Authorizator == nil {
		mw.Authorizator = func(userId string, request *rest.Request) bool {
			return true
		}
	}

	return func(writer rest.ResponseWriter, request *rest.Request) { mw.middlewareImpl(writer, request, handler) }
}

func (mw *JWTMiddleware) middlewareImpl(writer rest.ResponseWriter, request *rest.Request, handler rest.HandlerFunc) {
	token, err := parseToken(request, mw.Key)

	if err != nil {
		mw.unauthorized(writer)
		return
	}

	id := token.Claims["id"].(string)
	role := token.Claims["role"].(string)

	if !mw.Authorizator(id, request) {
		mw.unauthorized(writer)
		return
	}

	request.Env["REMOTE_USER"] = id
	request.Env["USER_ROLE"] = role
	handler(writer, request)
}

type login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// Handler that clients can use to get a jwt token.
// Payload needs to be json in the form of {"username": "USERNAME", "password": "PASSWORD"}.
// Reply will be of the form {"token": "TOKEN"}.
func (mw *JWTMiddleware) LoginHandler(writer rest.ResponseWriter, request *rest.Request) {
	login_vals := login{}
	err := request.DecodeJsonPayload(&login_vals)

	if err != nil {
		mw.unauthorized(writer)
		return
	}

	isAuthed, role := mw.Authenticator(login_vals.Username, login_vals.Password)
	if !isAuthed {
		mw.unauthorized(writer)
		return
	}

	token := jwt.New(jwt.GetSigningMethod(mw.SigningAlgorithm))
	token.Claims["id"] = login_vals.Username
	token.Claims["role"] = role
	token.Claims["exp"] = time.Now().Add(mw.Timeout).Unix()
	if mw.MaxRefresh != 0 {
		token.Claims["orig_iat"] = time.Now().Unix()
	}
	tokenString, err := token.SignedString(mw.Key)

	if err != nil {
		mw.unauthorized(writer)
		return
	}

	writer.WriteJson(&map[string]string{"token": tokenString})
}

func parseToken(request *rest.Request, key []byte) (*jwt.Token, error) {
	authHeader := request.Header.Get("Authorization")

	if authHeader == "" {
		return nil, errors.New("Auth header empty")
	}

	parts := strings.SplitN(authHeader, " ", 2)
	if !(len(parts) == 2 && parts[0] == "Bearer") {
		return nil, errors.New("Invalid auth header")
	}

	return jwt.Parse(parts[1], func(token *jwt.Token) (interface{}, error) {
		return key, nil
	})
}

type token struct {
	Token string `json:"token"`
}

// Handler that clients can use to refresh their token. The token still needs to be valid on refresh.
// Shall be put under an endpoint that is using the JWTMiddleware.
// Reply will be of the form {"token": "TOKEN"}.
func (mw *JWTMiddleware) RefreshHandler(writer rest.ResponseWriter, request *rest.Request) {
	token, err := parseToken(request, mw.Key)

	// Token should be valid anyway as the RefreshHandler is authed
	if err != nil {
		mw.unauthorized(writer)
		return
	}

	origIat := int64(token.Claims["orig_iat"].(float64))

	if origIat < time.Now().Add(-mw.MaxRefresh).Unix() {
		mw.unauthorized(writer)
		return
	}

	newToken := jwt.New(jwt.GetSigningMethod(mw.SigningAlgorithm))
	newToken.Claims["id"] = token.Claims["id"]
	newToken.Claims["role"] = token.Claims["role"]
	newToken.Claims["exp"] = time.Now().Add(mw.Timeout).Unix()
	newToken.Claims["orig_iat"] = origIat
	tokenString, err := newToken.SignedString(mw.Key)

	if err != nil {
		mw.unauthorized(writer)
		return
	}

	writer.WriteJson(&map[string]string{"token": tokenString})
}

func (mw *JWTMiddleware) unauthorized(writer rest.ResponseWriter) {
	writer.Header().Set("WWW-Authenticate", "JWT realm="+mw.Realm)
	rest.Error(writer, "Not Authorized", http.StatusUnauthorized)
}

**Comment by StephanDollberg** [comment]
Hi,

This is definitely an idea worth thinking about. It could maybe even be generalized.

Could you however move your code out of the comment into a gist or something so that it is easier to look at?

Cheers,
Stephan

**Comment by john-qin** [comment]
sorry about that, update my post and move the code to gist. hopefully it helps others with similar issues.

StephanDollberg, I have another question to ask.  with this middleware, it will apply to all the APIs.  but some of the APIs like view the article, user does not need to log in. only if they post a new article, they are required to get authenticated.  how can I use this middleware for only some of the APIs.

```
main_api := rest.NewApi()
main_api.Use(&jwt_middleware)
main_api.Use(rest.DefaultDevStack...)
main_api_router, _ := rest.MakeRouter(
    &rest.Route{"GET", "/GetTopTenPosts", getTopTenPosts},  // this one I dont need the jwt middleware, how do i exclude it???
    &rest.Route{"GET", "/auth_test", handle_auth},
    &rest.Route{"GET", "/refresh_token", jwt_middleware.RefreshHandler})
main_api.SetApp(main_api_router)
```

**Comment by StephanDollberg** [comment]
Thanks, for the update. I will have a look and think about it.

Well, you could simply use another Api object for the un-authed endpoints as you do with the login handler and use different base routes like `/api/` and `/api/auth/`.

However, I assume you want to use the same base route for both of them. If that is the case then I think it is not possible because of how the Go http server works. Given that this is a general thing it might be worth to ask on `go-json-rest`.
